# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('0', {'color': '#f00', 'name': 'hi'}), ('1', {'color': '#ff8a00', 'name': 'normal'}), ('2', {'color': '#fff', 'name': 'low'})], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['priority', 'deadline'],
            },
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todos.Project'),
        ),
    ]
